[env:ATmega328P_XMINI]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_protocol = custom
monitor_echo = yes
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    $BOARD_MCU
    -c
    xplainedmini
    -P
    usb
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
build_flags = -Wl,-u,vfprintf -lprintf_flt -lm
lib_ldf_mode = deep+
lib_deps = 
    SPI
    Wire
    marcoschwartz/LiquidCrystal_I2C
    adafruit/RTClib
    bogde/HX711